spring:
  application:
    name: payment-service8001
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/mq?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 0

mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
server:
  port: 8001
# Logger Config
logging:
  level:
    com.qiangzi.springcloud.payment.mapper: debug
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka