server:
  port: 80

spring:
  application:
    name: consul-consumer-payment80
  ####consul注册中心地址
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        #hostname: 127.0.0.1
        service-name: ${spring.application.name}
logging:
  level:
    # feign日志以什么级别监控哪个接口
    com.qiangzi.springcloud.order.api.PaymentFeign: debug

feign:
  hystrix:
    enabled: true